/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MyHardware */

#ifndef _Included_MyHardware
#define _Included_MyHardware
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MyHardware
 * Method:    ledOpen
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_MyHardware_ledOpen
  (JNIEnv *, jclass);

/*
 * Class:     MyHardware
 * Method:    ledClose
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_MyHardware_ledClose
  (JNIEnv *, jclass);

/*
 * Class:     MyHardware
 * Method:    ledCrtl
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_MyHardware_ledCrtl
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
